[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build", "cp -r .next/static .next/standalone/.next/static", "cp -r public .next/standalone/public || mkdir -p .next/standalone/public"]

[start]
cmd = "node .next/standalone/server.js"

[variables]
NODE_ENV = "production"
HOSTNAME = "0.0.0.0"
